version: '3.2'
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./app:/app
    - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
    - php
  php:
    build:
      context: ./
      dockerfile: ./php-fpm.dockerfile
    volumes:
    - ./app:/app
  composer:
    build:
      context: ./
      dockerfile: ./composer.dockerfile
    command: install
    volumes:
    - ./app:/app